version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: digital_wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wallet-network

  backend:
    build: ./digital-wallet-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/digital_wallet
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgres
    networks:
      - wallet-network

  frontend:
    build: ./digital_wallet_app
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8081/api
    depends_on:
      - backend
    networks:
      - wallet-network

volumes:
  postgres_data:

networks:
  wallet-network:
    driver: bridge